In [1]:
import pandas as pd

In [3]:
mvps = pd.read_csv("mvps.csv")

In [5]:
mvps.head()

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,year
0,0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991

In [7]:
mvps = mvps[["Player", "year", "Pts Won", "Pts Max", "Share"]]

In [8]:
mvps.head()

            Player  year  Pts Won  Pts Max  Share
0   Michael Jordan  1991    891.0      960  0.928
1    Magic Johnson  1991    497.0      960  0.518
2   David Robinson  1991    476.0      960  0.496
3  Charles Barkley  1991    222.0      960  0.231
4      Karl Malone  1991    142.0      960  0.148

In [9]:
players = pd.read_csv("players.csv")

In [10]:
players.head()

,Unnamed: 0,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,year
0,0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991

In [11]:
del players["Unnamed: 0"]
del players["Rk"]

In [12]:
players

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,year
0,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,.474,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,.413,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,.509,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,.394,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,.462,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18039,Delon Wright,PG,28,SAC,27,8,25.8,3.9,8.3,.462,...,1.0,2.9,3.9,3.6,1.6,0.4,1.3,1.1,10.0,2021
18040,Thaddeus Young,PF,32,CHI,68,23,24.3,5.4,9.7,.559,...,2.5,3.8,6.2,4.3,1.1,0.6,2.0,2.2,12.1,2021
18041,Trae Young,PG,22,ATL,63,63,33.7,7.7,17.7,.438,...,0.6,3.3,3.9,9.4,0.8,0.2,4.1,1.8,25.3,2021
18042,Cody Zeller,C,28,CHO,48,21,20.9,3.8,6.8,.559,...,2.5,4.4,6.8,1.8,0.6,0.4,1.1,2.5,9.4,2021
18043,Ivica Zubac,C,23,LAC,72,33,22.3,3.6,5.5,.652,...,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0,2021

In [14]:
players["Player"].head(30)

0         Alaa Abdelnaby
1     Mahmoud Abdul-Rauf
2             Mark Acres
3          Michael Adams
4           Mark Aguirre
5            Danny Ainge
6            Mark Alarie
7           Steve Alford
8          Greg Anderson
9          Greg Anderson
10         Greg Anderson
11         Greg Anderson
12         Nick Anderson
13          Ron Anderson
14       Willie Anderson
15        Michael Ansley
16        B.J. Armstrong
17         Vincent Askew
18          Keith Askins
19           Miloš Babić
20          Thurl Bailey
21           Cedric Ball
22         Ken Bannister
23      Charles Barkley*
24           Dana Barros
25           John Battle
26          Kenny Battle
27          Kenny Battle
28          Kenny Battle
29       William Bedford
Name: Player, dtype: object

In [17]:
players["Player"] = players["Player"].str.replace("*","", regex=False)

In [18]:
players["Player"].head(30)

0         Alaa Abdelnaby
1     Mahmoud Abdul-Rauf
2             Mark Acres
3          Michael Adams
4           Mark Aguirre
5            Danny Ainge
6            Mark Alarie
7           Steve Alford
8          Greg Anderson
9          Greg Anderson
10         Greg Anderson
11         Greg Anderson
12         Nick Anderson
13          Ron Anderson
14       Willie Anderson
15        Michael Ansley
16        B.J. Armstrong
17         Vincent Askew
18          Keith Askins
19           Miloš Babić
20          Thurl Bailey
21           Cedric Ball
22         Ken Bannister
23       Charles Barkley
24           Dana Barros
25           John Battle
26          Kenny Battle
27          Kenny Battle
28          Kenny Battle
29       William Bedford
Name: Player, dtype: object

In [19]:
players.head(20)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,year
0,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,.474,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,.413,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,.509,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,.394,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,.462,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
5,Danny Ainge,SG,31,POR,80,0,21.4,4.2,8.9,.472,...,0.6,2.0,2.6,3.6,0.8,0.2,1.3,2.4,11.1,1991
6,Mark Alarie,PF,27,WSB,42,1,14.0,2.4,5.4,.440,...,1.0,1.8,2.8,1.1,0.4,0.2,1.0,2.1,5.8,1991
7,Steve Alford,PG,26,DAL,34,0,6.9,1.7,3.4,.504,...,0.3,0.4,0.7,0.6,0.2,0.0,0.5,0.3,4.4,1991
8,Greg Anderson,PF,26,TOT,68,2,13.6,1.7,4.0,.430,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
9,Greg Anderson,PF,26,MIL,26,0,9.5,1.0,2.8,.370,...,1.0,1.9,2.9,0.1,0.3,0.3,0.8,1.1,2.7,1991
10,Greg Anderson,PF,26,NJN,1,0,18.0,4.0,4.0,1.000,...,4.0,2.0,6.0,1.0,2.0,0.0,1.0,4.0,8.0,1991
11,Greg Anderson,PF,26,DEN,41,2,16.1,2.1,4.7,.440,...,1.6,4.1,5.8,0.3,0.6,0.9,1.5,2.6,5.2,1991
12,Nick Anderson,SG,23,ORL,70,42,28.2,5.7,12.2,.467,...,1.3,4.2,5.5,1.5,1.1,0.6,1.6,2.1,14.1,1991
13,Ron Anderson,SF,32,PHI,82,13,28.5,6.2,12.9,.485,...,1.3,3.2,4.5,1.4,0.8,0.2,1.2,2.0,14.6,1991
14,Willie Anderson,SG,24,SAS,75,75,34.6,6.0,13.2,.457,...,0.9,3.8,4.7,4.8,1.1,0.6,2.2,3.0,14.4,1991
15,Michael Ansley,SF,23,ORL,67,1,13.1,2.1,3.9,.548,...,1.8,2.0,3.8,0.4,0.4,0.1,0.5,1.9,5.7,1991
16,B.J. Armstrong,PG,23,CHI,82,0,21.1,3.7,7.7,.481,...,0.3,1.5,1.8,3.7,0.9,0.0,1.3,1.4,8.8,1991
17,Vincent Askew,SG,24,GSW,7,0,12.1,1.7,3.6,.480,...,1.0,0.6,1.6,1.9,0.3,0.0,0.9,3.0,4.7,1991
18,Keith Askins,SF,23,MIA,39,1,6.8,0.9,2.1,.420,...,0.8,1.0,1.7,0.5,0.4,0.3,0.3,1.2,2.2,1991
19,Miloš Babić,PF,22,CLE,12,0,4.3,0.5,1.6,.316,...,0.5,0.3,0.8,0.3,0.1,0.1,0.4,0.6,1.6,1991

In [27]:
players.groupby(["Player","year"]).get_group(("Mark Alarie", 1991))

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,year
6,Mark Alarie,PF,27,WSB,42,1,14.0,2.4,5.4,.440,...,1.0,1.8,2.8,1.1,0.4,0.2,1.0,2.1,5.8,1991

In [28]:
def single_row(df):
    if df.shape[0]==1:
        return df
    else :
        row = df[df["Tm"] == "TOT"]
        row["Tm"] = df.iloc[-1:]["Tm"]
        return row

players = players.groupby(["Player","year"]).apply(single_row)

In [31]:
players

                                  Player Pos Age   Tm   G  GS    MP   FG  \
Player         year
A.C. Green     1991 164       A.C. Green  PF  27  LAL  82  21  26.4  3.1
               1992 633       A.C. Green  PF  28  LAL  82  53  35.4  4.7
               1993 1092      A.C. Green  PF  29  LAL  82  55  34.4  4.6
               1994 1579      A.C. Green  PF  30  PHO  82  55  34.5  5.7
               1995 2067      A.C. Green  SF  31  PHO  82  52  32.8  3.8
...                                  ...  ..  ..  ...  ..  ..   ...  ...
Željko Rebrača 2002 6095  Željko Rebrača   C  29  DET  74   4  15.9  2.6
               2003 6595  Željko Rebrača   C  30  DET  30  12  16.3  2.7
               2004 7176  Željko Rebrača   C  31  NaN  24   2  11.4  1.4
               2005 7776  Željko Rebrača   C  32  LAC  58   2  16.0  2.3
               2006 8370  Željko Rebrača   C  33  LAC  29   2  14.2  1.8

                           FGA   FG%  ...  ORB  DRB  TRB  AST  STL  BLK  TOV  \
Player         year                   ...
A.C. Green     1991 164    6.6  .476  ...  2.5  3.8  6.3  0.9  0.7  0.3  1.2
               1992 633    9.8  .476  ...  3.7  5.6  9.3  1.4  1.1  0.4  1.4
               1993 1092   8.6  .537  ...  3.5  5.2  8.7  1.4  1.1  0.5  1.4
               1994 1579  11.3  .502  ...  3.4  5.8  9.2  1.7  0.9  0.5  1.2
               1995 2067   7.5  .504  ...  2.4  5.8  8.2  1.5  0.7  0.4  1.4
...                        ...   ...  ...  ...  ...  ...  ...  ...  ...  ...
Željko Rebrača 2002 6095   5.1  .505  ...  1.1  2.8  3.9  0.5  0.4  1.0  1.1
               2003 6595   4.8  .552  ...  0.9  2.2  3.1  0.3  0.2  0.6  1.0
               2004 7176   3.2  .442  ...  1.0  1.5  2.4  0.3  0.2  0.5  0.7
               2005 7776   4.0  .568  ...  0.8  2.3  3.2  0.4  0.2  0.7  0.8
               2006 8370   3.3  .542  ...  0.4  1.8  2.2  0.3  0.2  0.7  0.8

                           PF   PTS    year
Player         year
A.C. Green     1991 164   1.4   9.1  1991.0
               1992 633   1.7  13.6  1992.0
               1993 1092  1.8  12.8  1993.0
               1994 1579  1.7  14.7  1994.0
               1995 2067  1.8  11.2  1995.0
...                       ...   ...     ...
Željko Rebrača 2002 6095  2.6   6.9  2002.0
               2003 6595  2.6   6.6  2003.0
               2004 7176  2.2   3.8  2004.0
               2005 7776  2.2   5.8  2005.0
               2006 8370  2.0   4.7  2006.0

[14128 rows x 30 columns]

In [32]:
players.index = players.index.droplevel()

In [33]:
players.index = players.index.droplevel()

In [34]:
players

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,year
164,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,2.5,3.8,6.3,0.9,0.7,0.3,1.2,1.4,9.1,1991.0
633,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,3.7,5.6,9.3,1.4,1.1,0.4,1.4,1.7,13.6,1992.0
1092,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,3.5,5.2,8.7,1.4,1.1,0.5,1.4,1.8,12.8,1993.0
1579,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,3.4,5.8,9.2,1.7,0.9,0.5,1.2,1.7,14.7,1994.0
2067,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,2.4,5.8,8.2,1.5,0.7,0.4,1.4,1.8,11.2,1995.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6095,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,.505,...,1.1,2.8,3.9,0.5,0.4,1.0,1.1,2.6,6.9,2002.0
6595,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,.552,...,0.9,2.2,3.1,0.3,0.2,0.6,1.0,2.6,6.6,2003.0
7176,Željko Rebrača,C,31,NaN,24,2,11.4,1.4,3.2,.442,...,1.0,1.5,2.4,0.3,0.2,0.5,0.7,2.2,3.8,2004.0
7776,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.8,2.3,3.2,0.4,0.2,0.7,0.8,2.2,5.8,2005.0
8370,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.4,1.8,2.2,0.3,0.2,0.7,0.8,2.0,4.7,2006.0

In [35]:
combined = players.merge(mvps, how="outer", on=["Player", "year"])

In [36]:
combined

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991.0,NaN,NaN,NaN
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992.0,NaN,NaN,NaN
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993.0,NaN,NaN,NaN
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994.0,NaN,NaN,NaN
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14123,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002.0,NaN,NaN,NaN
14124,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003.0,NaN,NaN,NaN
14125,Željko Rebrača,C,31,NaN,24,2,11.4,1.4,3.2,.442,...,0.3,0.2,0.5,0.7,2.2,3.8,2004.0,NaN,NaN,NaN
14126,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005.0,NaN,NaN,NaN
14127,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006.0,NaN,NaN,NaN

In [37]:
combined[["Pts Won","Pts Max","Share"]] = combined[["Pts Won","Pts Max","Share"]].fillna(0)

In [38]:
combined

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991.0,0.0,0.0,0.0
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992.0,0.0,0.0,0.0
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993.0,0.0,0.0,0.0
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994.0,0.0,0.0,0.0
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14123,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002.0,0.0,0.0,0.0
14124,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003.0,0.0,0.0,0.0
14125,Željko Rebrača,C,31,NaN,24,2,11.4,1.4,3.2,.442,...,0.3,0.2,0.5,0.7,2.2,3.8,2004.0,0.0,0.0,0.0
14126,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005.0,0.0,0.0,0.0
14127,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006.0,0.0,0.0,0.0

In [39]:
teams = pd.read_csv("teams.csv")

In [40]:
teams

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
...,...,...,...,...,...,...,...,...,...,...
1028,13,42,30,.583,—,112.4,110.2,2.26,2021,Dallas Mavericks*
1029,14,38,34,.528,4.0,113.3,112.3,1.07,2021,Memphis Grizzlies*
1030,15,33,39,.458,9.0,111.1,112.8,-1.58,2021,San Antonio Spurs
1031,16,31,41,.431,11.0,114.6,114.9,-0.20,2021,New Orleans Pelicans
1032,17,17,55,.236,25.0,108.8,116.7,-7.50,2021,Houston Rockets

In [45]:
teams = teams[~teams["W"].str.contains("Division")]

In [46]:
teams.head(30)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
7,7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls*
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*
10,10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks*
11,11,41,41,.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers*
12,12,33,49,.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers
13,13,26,56,.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets
15,1,55,27,.671,—,107.1,102.6,4.30,1991,San Antonio Spurs*
16,2,54,28,.659,1.0,104.0,100.7,3.18,1991,Utah Jazz*
17,3,52,30,.634,3.0,106.7,103.2,3.27,1991,Houston Rockets*
18,4,31,51,.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic
19,5,29,53,.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves
20,6,28,54,.341,27.0,99.9,104.5,-4.27,1991,Dallas Mavericks
21,7,20,62,.244,35.0,119.9,130.8,-10.31,1991,Denver Nuggets
23,9,63,19,.768,—,114.7,106.0,8.47,1991,Portland Trail Blazers*
24,10,58,24,.707,5.0,106.3,99.6,6.73,1991,Los Angeles Lakers*
25,11,55,27,.671,8.0,114.0,107.5,6.49,1991,Phoenix Suns*
26,12,44,38,.537,19.0,116.6,115.0,1.72,1991,Golden State Warriors*
27,13,41,41,.500,22.0,106.6,105.4,1.31,1991,Seattle SuperSonics*
28,14,31,51,.378,32.0,103.5,107.0,-3.16,1991,Los Angeles Clippers
29,15,25,57,.305,38.0,96.7,103.5,-6.27,1991,Sacramento Kings
30,0,51,31,.622,—,106.6,103.0,3.41,1992,Boston Celtics*
31,1,51,31,.622,—,101.6,97.7,3.67,1992,New York Knicks*
32,2,40,42,.488,11.0,105.4,107.1,-1.54,1992,New Jersey Nets*

In [47]:
teams["Team"] = teams["Team"].str.replace("*","", regex=False)

<ipython-input-47-cf1b33d43eef>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teams["Team"] = teams["Team"].str.replace("*","", regex=False)

In [48]:
teams.head(30)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
7,7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks
10,10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks
11,11,41,41,.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers
12,12,33,49,.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers
13,13,26,56,.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets
15,1,55,27,.671,—,107.1,102.6,4.30,1991,San Antonio Spurs
16,2,54,28,.659,1.0,104.0,100.7,3.18,1991,Utah Jazz
17,3,52,30,.634,3.0,106.7,103.2,3.27,1991,Houston Rockets
18,4,31,51,.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic
19,5,29,53,.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves
20,6,28,54,.341,27.0,99.9,104.5,-4.27,1991,Dallas Mavericks
21,7,20,62,.244,35.0,119.9,130.8,-10.31,1991,Denver Nuggets
23,9,63,19,.768,—,114.7,106.0,8.47,1991,Portland Trail Blazers
24,10,58,24,.707,5.0,106.3,99.6,6.73,1991,Los Angeles Lakers
25,11,55,27,.671,8.0,114.0,107.5,6.49,1991,Phoenix Suns
26,12,44,38,.537,19.0,116.6,115.0,1.72,1991,Golden State Warriors
27,13,41,41,.500,22.0,106.6,105.4,1.31,1991,Seattle SuperSonics
28,14,31,51,.378,32.0,103.5,107.0,-3.16,1991,Los Angeles Clippers
29,15,25,57,.305,38.0,96.7,103.5,-6.27,1991,Sacramento Kings
30,0,51,31,.622,—,106.6,103.0,3.41,1992,Boston Celtics
31,1,51,31,.622,—,101.6,97.7,3.67,1992,New York Knicks
32,2,40,42,.488,11.0,105.4,107.1,-1.54,1992,New Jersey Nets

In [49]:
teams["Team"].unique()

array(['Boston Celtics', 'Philadelphia 76ers', 'New York Knicks',
       'Washington Bullets', 'New Jersey Nets', 'Miami Heat',
       'Chicago Bulls', 'Detroit Pistons', 'Milwaukee Bucks',
       'Atlanta Hawks', 'Indiana Pacers', 'Cleveland Cavaliers',
       'Charlotte Hornets', 'San Antonio Spurs', 'Utah Jazz',
       'Houston Rockets', 'Orlando Magic', 'Minnesota Timberwolves',
       'Dallas Mavericks', 'Denver Nuggets', 'Portland Trail Blazers',
       'Los Angeles Lakers', 'Phoenix Suns', 'Golden State Warriors',
       'Seattle SuperSonics', 'Los Angeles Clippers', 'Sacramento Kings',
       'Toronto Raptors', 'Vancouver Grizzlies', 'Washington Wizards',
       'Memphis Grizzlies', 'New Orleans Hornets', 'Charlotte Bobcats',
       'New Orleans/Oklahoma City Hornets', 'Oklahoma City Thunder',
       'Brooklyn Nets', 'New Orleans Pelicans'], dtype=object)

In [50]:
combined["Tm"].unique()

array(['LAL', 'PHO', nan, 'DAL', 'MIA', 'CLE', 'WSB', 'CHI', 'GSW', 'IND',
       'WAS', 'MIN', 'BOS', 'HOU', 'ORL', 'NOH', 'TOR', 'CHO', 'POR',
       'PHI', 'UTA', 'MIL', 'SEA', 'NJN', 'LAC', 'OKC', 'ATL', 'CHA',
       'DEN', 'NYK', 'NOP', 'BRK', 'DET', 'SAS', 'MEM', 'CHH', 'SAC',
       'VAN', 'NOK', 'Tm'], dtype=object)

In [57]:
nicknames = {}
with open("nickname.csv") as f:
    lines = f.readlines()
    for line in lines[1:]:
        abbrev, name = line.replace("\n","").split(",")
        nicknames[abbrev] = name

In [58]:
combined["Tm"].map(nicknames)

0          Los Angeles Lakers
1          Los Angeles Lakers
2          Los Angeles Lakers
3                Phoenix Suns
4                Phoenix Suns
                 ...
14123         Detroit Pistons
14124         Detroit Pistons
14125                     NaN
14126    Los Angeles Clippers
14127    Los Angeles Clippers
Name: Tm, Length: 14128, dtype: object

In [59]:
combined["Team"] = combined["Tm"].map(nicknames)

In [60]:
combined.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,year,Pts Won,Pts Max,Share,Team
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,1991.0,0.0,0.0,0.0,Los Angeles Lakers
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.1,0.4,1.4,1.7,13.6,1992.0,0.0,0.0,0.0,Los Angeles Lakers
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,1993.0,0.0,0.0,0.0,Los Angeles Lakers
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,1994.0,0.0,0.0,0.0,Phoenix Suns
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,1995.0,0.0,0.0,0.0,Phoenix Suns

In [61]:
stats = combined.merge(teams, how="outer", on=["Team", "year"])

In [62]:
stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Share,Team,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,.477,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,.455,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,.340,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,.492,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14123,Jordan McLaughlin,PG,23,MIN,30,2,19.7,2.9,5.9,.489,...,0.0,Minnesota Timberwolves,5.0,19,45,.297,22.5,113.3,117.5,-4.02
14124,Josh Okogie,SG,21,MIN,62,28,25.0,2.7,6.4,.427,...,0.0,Minnesota Timberwolves,5.0,19,45,.297,22.5,113.3,117.5,-4.02
14125,Karl-Anthony Towns,C,24,MIN,35,35,33.9,9.0,17.8,.508,...,0.0,Minnesota Timberwolves,5.0,19,45,.297,22.5,113.3,117.5,-4.02
14126,Kelan Martin,SF,24,MIN,31,4,16.0,2.3,5.8,.392,...,0.0,Minnesota Timberwolves,5.0,19,45,.297,22.5,113.3,117.5,-4.02
14127,Naz Reid,C,20,MIN,30,11,16.5,3.3,8.1,.412,...,0.0,Minnesota Timberwolves,5.0,19,45,.297,22.5,113.3,117.5,-4.02

In [63]:
del stats["Unnamed: 0"]

In [64]:
stats.dtypes

Player      object
Pos         object
Age         object
Tm          object
G           object
GS          object
MP          object
FG          object
FGA         object
FG%         object
3P          object
3PA         object
3P%         object
2P          object
2PA         object
2P%         object
eFG%        object
FT          object
FTA         object
FT%         object
ORB         object
DRB         object
TRB         object
AST         object
STL         object
BLK         object
TOV         object
PF          object
PTS         object
year       float64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W           object
L           object
W/L%        object
GB          object
PS/G        object
PA/G        object
SRS         object
dtype: object

In [65]:
stats = stats.apply(pd.to_numeric, errors="ignore")

In [66]:
stats.dtypes

Player      object
Pos         object
Age        float64
Tm          object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
year       float64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W          float64
L          float64
W/L%       float64
GB          object
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [67]:
stats["GB"].unique()

array(['5.0', '14.0', '23.0', '7.0', '—', nan, '42.0', '18.0', '6.0',
       '24.0', '26.0', '37.0', '29.0', '21.0', '28.0', '25.0', '8.0',
       '19.0', '1.0', '13.0', '3.0', '15.0', '9.0', '2.0', '35.0', '20.0',
       '11.0', '16.0', '41.0', '12.0', '10.0', '30.0', '34.0', '4.0',
       '1.5', '22.0', '51.0', '39.0', '18.5', '48.0', '40.0', '17.0',
       '46.0', '10.5', '32.0', '38.0', '27.0', '31.0', '33.0', '50.0',
       '43.0', '45.0', '25.5', '36.0', '3.5', '20.5', '11.5', '44.0',
       '52.0', '56.0', '2.5', '12.5', '32.5', '21.5', '4.5', '47.0',
       '22.5'], dtype=object)

In [68]:
stats["GB"] = stats["GB"].str.replace("—","0")
stats["GB"].unique()

array(['5.0', '14.0', '23.0', '7.0', '0', nan, '42.0', '18.0', '6.0',
       '24.0', '26.0', '37.0', '29.0', '21.0', '28.0', '25.0', '8.0',
       '19.0', '1.0', '13.0', '3.0', '15.0', '9.0', '2.0', '35.0', '20.0',
       '11.0', '16.0', '41.0', '12.0', '10.0', '30.0', '34.0', '4.0',
       '1.5', '22.0', '51.0', '39.0', '18.5', '48.0', '40.0', '17.0',
       '46.0', '10.5', '32.0', '38.0', '27.0', '31.0', '33.0', '50.0',
       '43.0', '45.0', '25.5', '36.0', '3.5', '20.5', '11.5', '44.0',
       '52.0', '56.0', '2.5', '12.5', '32.5', '21.5', '4.5', '47.0',
       '22.5'], dtype=object)

In [69]:
stats["GB"] = pd.to_numeric(stats["GB"])

In [70]:
stats.dtypes

Player      object
Pos         object
Age        float64
Tm          object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
year       float64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W          float64
L          float64
W/L%       float64
GB         float64
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [71]:
stats.to_csv("player_mvp_stats.csv")