In [83]:
#Libraries
import pandas as pd

In [84]:
stats = pd.read_csv("player_mvp_stats.csv")

In [85]:
stats

,Unnamed: 0,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
1,1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
2,2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
3,3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
4,4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,14087,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14088,14088,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14089,14089,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14090,14090,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14091,14091,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45

In [86]:
del stats["Unnamed: 0"]

In [87]:
pd.isnull(stats).sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          50
3P            0
3PA           0
3P%        2042
2P            0
2PA           0
2P%          84
eFG%         50
FT            0
FTA           0
FT%         462
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
dtype: int64

In [88]:
stats[pd.isnull(stats["3P%"])][["Player", "3PA"]]

                 Player  3PA
2        Elden Campbell  0.0
3         Irving Thomas  0.0
18           Jack Haley  0.0
20          Keith Owens  0.0
30      Benoit Benjamin  0.0
...                 ...  ...
14061    Evan Eschmeyer  0.0
14062  Gheorghe Mureșan  0.0
14064     Jim McIlvaine  0.0
14070  Mark Hendrickson  0.0
14071      Michael Cage  0.0

[2042 rows x 2 columns]

In [89]:
stats = stats.fillna(0)

In [90]:
stats.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS'],
      dtype='object')

In [91]:
predictors = ['Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P','3PA',
 '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB','DRB', 
 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year', 'W', 'L', 
 'W/L%', 'GB', 'PS/G','PA/G', 'SRS']

In [92]:
train = stats[stats["Year"] < 2021]
test = stats[stats["Year"] == 2021]

In [93]:
#!pip install sklearn
from sklearn.linear_model import Ridge

reg = Ridge(alpha=.1)

In [94]:
reg.fit(train[predictors], train["Share"])

Ridge(alpha=0.1)

In [95]:
predictions = reg.predict(test[predictors])

In [96]:
predictions = pd.DataFrame(predictions, columns=["predictions"], index= test.index)

In [97]:
predictions

       predictions
630       0.013567
631      -0.013756
632       0.002414
633      -0.004421
634       0.010734
...            ...
13897    -0.012571
13898    -0.011575
13899     0.016424
13900    -0.020434
13901    -0.005421

[540 rows x 1 columns]

In [98]:
combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)

In [99]:
combination

                       Player  Share  predictions
630              Aaron Gordon    0.0     0.013567
631             Austin Rivers    0.0    -0.013756
632                   Bol Bol    0.0     0.002414
633          Facundo Campazzo    0.0    -0.004421
634          Greg Whittington    0.0     0.010734
...                       ...    ...          ...
13897             Patty Mills    0.0    -0.012571
13898  Quinndary Weatherspoon    0.0    -0.011575
13899                Rudy Gay    0.0     0.016424
13900               Tre Jones    0.0    -0.020434
13901              Trey Lyles    0.0    -0.005421

[540 rows x 3 columns]

In [100]:
combination.sort_values("Share", ascending=False).head(10)

                      Player  Share  predictions
641             Nikola Jokić  0.961     0.154307
8624             Joel Embiid  0.580     0.162713
3651           Stephen Curry  0.449     0.142386
9907   Giannis Antetokounmpo  0.345     0.207436
1389              Chris Paul  0.138     0.072294
10997            Luka Dončić  0.042     0.151430
7464          Damian Lillard  0.038     0.116303
3536           Julius Randle  0.020     0.088878
3531            Derrick Rose  0.010     0.033000
11358            Rudy Gobert  0.008     0.095349

In [101]:
from sklearn.metrics import mean_squared_error

mean_squared_error(combination["Share"], combination["predictions"])

0.002666895456710409

In [102]:
combination["Share"].value_counts()

0.000    525
0.001      3
0.042      1
0.580      1
0.038      1
0.449      1
0.008      1
0.961      1
0.345      1
0.010      1
0.003      1
0.020      1
0.138      1
0.005      1
Name: Share, dtype: int64

In [103]:
combination = combination.sort_values("Share", ascending=False)
combination["Rk"] = list(range(1, combination.shape[0]+1))

In [104]:
combination.head(10)

                      Player  Share  predictions  Rk
641             Nikola Jokić  0.961     0.154307   1
8624             Joel Embiid  0.580     0.162713   2
3651           Stephen Curry  0.449     0.142386   3
9907   Giannis Antetokounmpo  0.345     0.207436   4
1389              Chris Paul  0.138     0.072294   5
10997            Luka Dončić  0.042     0.151430   6
7464          Damian Lillard  0.038     0.116303   7
3536           Julius Randle  0.020     0.088878   8
3531            Derrick Rose  0.010     0.033000   9
11358            Rudy Gobert  0.008     0.095349  10

In [105]:
combination = combination.sort_values("predictions", ascending=False)
combination["predicted_rk"] = list(range(1, combination.shape[0]+1))

In [106]:
combination.sort_values("Share", ascending=False).head(10)

                      Player  Share  predictions  Rk  predicted_rk
641             Nikola Jokić  0.961     0.154307   1             3
8624             Joel Embiid  0.580     0.162713   2             2
3651           Stephen Curry  0.449     0.142386   3             6
9907   Giannis Antetokounmpo  0.345     0.207436   4             1
1389              Chris Paul  0.138     0.072294   5            33
10997            Luka Dončić  0.042     0.151430   6             4
7464          Damian Lillard  0.038     0.116303   7            12
3536           Julius Randle  0.020     0.088878   8            24
3531            Derrick Rose  0.010     0.033000   9            76
11358            Rudy Gobert  0.008     0.095349  10            19

In [107]:
def find_ap(combination):
    actual = combination.sort_values("Share", ascending=False).head(5)
    predicted = combination.sort_values("predictions", ascending=False)
    ps=[]
    found = 0
    seen = 1
    for index, row in predicted.iterrows():
        if row["Player"] in actual["Player"].values :
            found +=1
            ps.append(found/seen)
        seen +=1
    return sum(ps)/len(ps)

In [108]:
find_ap(combination)

0.7636363636363636

In [111]:
years = list(range(1992,2022))

In [112]:
aps = []
all_predictions = []
for year in years :
    train = stats[stats["Year"] < year]
    test = stats[stats["Year"] == year]
    reg.fit(train[predictors], train["Share"])
    predictions = reg.predict(test[predictors])
    predictions = pd.DataFrame(predictions, columns=["predictions"], index= test.index)
    combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
    all_predictions.append(combination)
    aps.append(find_ap(combination))

In [113]:
sum(aps)/len(aps)

0.7363044752895939

In [114]:
def add_ranks(combination):
    combination = combination.sort_values("Share", ascending=False)
    combination["Rk"] = list(range(1, combination.shape[0]+1))
    combination = combination.sort_values("predictions", ascending=False)
    combination["predicted_rk"] = list(range(1, combination.shape[0]+1))
    combination["Diff"] = combination["Rk"] - combination["predicted_rk"]
    return combination

In [117]:
add_ranks(all_predictions[1]).sort_values("Diff", ascending=False)

                     Player  Share  predictions   Rk  predicted_rk  Diff
7039         Hersey Hawkins    0.0     0.042034  388            32   356
7610           Eric Murdock    0.0     0.053217  373            23   350
4892           Tim Hardaway    0.0     0.058564  363            21   342
4895   Šarūnas Marčiulionis    0.0     0.060329  360            20   340
7040          Jeff Hornacek    0.0     0.031739  387            48   339
...                     ...    ...          ...  ...           ...   ...
10915          Chuck Person    0.0    -0.048026   56           384  -328
12106      Lamont Strothers    0.0    -0.053797   54           385  -331
12102      Dexter Cambridge    0.0    -0.022657   16           350  -334
12113           Terry Davis    0.0    -0.057083   46           386  -340
12105           Jim Jackson    0.0    -0.079165   35           390  -355

[390 rows x 6 columns]